/* content.js — 슬라이드 메타데이터 (Content Driven 원칙)
 * 씬의 마크업은 index.html에, 목차·노트·전환 설정은 여기서 관리한다. */
window.CONTENT = [
  {
    id: "opening",
    section: "Opening",
    title: "AI Native Campus로의 전환",
    transition: "fade",
    art: "radial-gradient(circle at 30% 25%, rgba(79,124,255,0.5), transparent 60%), radial-gradient(circle at 80% 75%, rgba(0,229,255,0.3), transparent 55%)",
    notes: "발표 첫인상. 캠퍼스 영상 위 타이틀 리빌과 거버닝 카피가 자동으로 이어짐. 'AI를 도입하는 대학에서, AI로 태어나는 대학으로'를 힘 있게 낭독.",
  },
  {
    id: "context",
    section: "Background",
    title: "AI는 이미 학습과 행정의 기본 도구가 되었다",
    transition: "blur-fade",
    art: "linear-gradient(100deg, rgba(26,29,38,0.9) 0 50%, rgba(20,34,77,0.9) 50% 100%)",
    notes: "금지의 시대→권장의 시대 인식 전환. 마우스를 좌우로 움직이며 Before/After를 보여줄 것. 진행 입력 한 번이면 After 리빌과 학습·연구·행정·업무 칩이 자동으로 이어짐.",
  },
  {
    id: "voices",
    section: "Problem",
    title: "현장의 목소리",
    transition: "push",
    art: "radial-gradient(circle at 50% 40%, rgba(124,92,255,0.45), transparent 60%)",
    notes: "학생→교수→운영자 순서로 증언 카드 회전. 각 페르소나 대사를 1개씩만 읽고 템포 유지. 마지막 결론 카피: '뒷받침할 AI 통합 인프라가 없다'.",
  },
  {
    id: "painpoints",
    section: "Problem",
    title: "대학이 안고 있는 복합적인 Pain Point",
    transition: "fade",
    art: "radial-gradient(circle at 25% 30%, rgba(255,92,122,0.35), transparent 55%), radial-gradient(circle at 75% 70%, rgba(79,124,255,0.3), transparent 55%)",
    notes: "카드 4장이 자동으로 하나씩 등장하고 얽힘 라인이 이어서 그려짐. 각 문제를 짚은 뒤 '문제는 서로 얽혀 있다' 강조 — 개별 해결이 불가능함을 설득.",
  },
  {
    id: "solution",
    section: "Solution",
    title: "단 하나의 통합 인프라",
    transition: "morph",
    art: "radial-gradient(circle at 50% 50%, rgba(0,229,255,0.4), transparent 58%)",
    notes: "흩어진 전공·자원 노드를 보여준 뒤(호버로 툴팁 시연 가능), 스텝2에서 중앙으로 응집. 핵심 문장: '모든 전공의 기본 도구로 내재화한다'.",
  },
  {
    id: "architecture",
    section: "Architecture",
    title: "AI 인프라 표준 프레임워크",
    transition: "zoom",
    art: "linear-gradient(160deg, rgba(39,87,214,0.35), rgba(124,92,255,0.25) 55%, rgba(12,138,95,0.25))",
    notes: "스텝①: 이용자 트랙 3장 등장. 진행 입력 한 번(스텝②)이면 API/vGPU 커넥터+Slurm/K8s → 내부 모듈 4종 → VDI → 외부 LLM·전체 조망이 자동으로 이어짐(약 7초). 조망 상태에서 트랙에 호버하면 자원 경로가 하이라이트됨.",
  },
  /* ══════ 02 덱 · 기술 상세 ══════ */
  {
    id: "dstation",
    section: "Dstation",
    title: "Dstation — VDI",
    transition: "fly",
    art: "radial-gradient(circle at 65% 40%, rgba(79,124,255,0.5), transparent 60%)",
    notes: "챕터1 진입. VDI 배경 영상 위 타이틀 자동 리빌. '시공간 제약 없는 학습'을 강조하고 다음 장에서 개념을 설명.",
  },
  {
    id: "vdi-concept",
    section: "Dstation",
    title: "데스크톱 가상화 개념",
    transition: "fade",
    art: "linear-gradient(140deg, rgba(39,87,214,0.35), rgba(0,166,196,0.25))",
    notes: "스텝: ①좌측 메시지 → ②Cloud Center → ③Any Where/Device 칩 + 자동 시연 1회 → ④핵심 카피 강조. 단말 칩에 호버하면 가상PC로 파티클 왕복 + 미러링 시연 가능.",
  },
  {
    id: "estation",
    section: "Estation",
    title: "Estation — GPU Slicing",
    transition: "fly",
    art: "radial-gradient(circle at 60% 45%, rgba(25,201,141,0.45), transparent 60%)",
    notes: "챕터2 진입. 스텝②에서 '9배'가 카운트업되며 확대 강조 — '고가의 GPU 활용률이 9배 향상'을 힘 있게.",
  },
  {
    id: "gpu-slicing",
    section: "Estation",
    title: "유동적 vGPU 분할 비교",
    transition: "wipe",
    art: "linear-gradient(100deg, rgba(255,92,122,0.3) 0 48%, rgba(25,201,141,0.35) 52% 100%)",
    notes: "스텝: ①전통 방식(15%) → ②Tilon GPU 등장 → ③8장 레이어 슬라이싱 분해 + 워크로드 연결 → ④활용률 게이지 레이스(15% vs 90%). 우측 레이어에 호버하면 레이어:워크로드 매핑 시연.",
  },
  {
    id: "daas-value",
    section: "Estation",
    title: "DaaS + GPU Slicing 가치",
    transition: "push",
    art: "radial-gradient(circle at 40% 60%, rgba(25,201,141,0.4), transparent 58%)",
    notes: "스텝: 가치①(활용률 카운터)→②(고성능 워크로드)→③(64FPS/8K 프레임 비교)→④MIG 비교표→⑤활용 분야+결론. 5FPS vs 64FPS 시뮬레이션 박스로 체감 비교.",
  },
  {
    id: "istation",
    section: "iStation",
    title: "iStation — Sovereign AI",
    transition: "fly",
    art: "radial-gradient(circle at 60% 40%, rgba(180,79,255,0.45), transparent 60%)",
    notes: "챕터3 진입. Internal AI / AI Router / Tokenizer 3개 키워드 칩이 순차 리빌. '데이터 주권' 인상 형성.",
  },
  {
    id: "istation-features",
    section: "iStation",
    title: "iStation 3대 특징",
    transition: "fade",
    art: "linear-gradient(150deg, rgba(124,92,255,0.4), rgba(30,20,64,0.5))",
    notes: "스텝: ①카드 3장 등장 → ②일괄 플립 시연(뒷면 상세 노출) → ③핵심 문장 강조. 카드 호버=플립, 클릭=고정.",
  },
  {
    id: "scheduling",
    section: "iStation",
    title: "지능형 자원 스케줄링",
    transition: "blur-fade",
    art: "linear-gradient(100deg, rgba(18,50,90,0.6) 0 50%, rgba(5,7,15,0.8) 50% 100%)",
    notes: "시그니처 장표. 스텝: ①주간(수백 명 미세 분할) → ②야간 전환(대규모 집중 할당) → ③24시간 결론. GPU 코어·매트릭스·연구 블록에 호버 툴팁.",
  },
  {
    id: "jeju-case",
    section: "Case",
    title: "제주대학교 Sovereign AI 구축",
    transition: "push",
    art: "linear-gradient(120deg, rgba(60,33,120,0.55), rgba(28,20,64,0.6))",
    notes: "스텝: ①인사말 타이핑 → ②질문/답변 데모 재생(6초 이내) → ③특징 노드 4종 연결 → ④의의 강조. 노드 호버 시 채팅에서 해당 특징 위치가 하이라이트. ※연출된 예시임을 안내.",
  },
  {
    id: "closing",
    section: "Closing",
    title: "자체 AI 인프라 = 정부사업 가산점",
    transition: "particle",
    art: "radial-gradient(circle at 50% 45%, rgba(0,229,255,0.35), transparent 58%), radial-gradient(circle at 30% 70%, rgba(79,124,255,0.3), transparent 55%)",
    notes: "클로징. 스텝: ①헤드라인 → ②기존 방식(단순 소비) → ③자체 보유(가치 4종) → ④정부사업 무기 + 최종 메시지(파티클 응집). 마지막 입력 시 Overview가 열려 Q&A 대응.",
  },
  {
    id: "tstation",
    section: "Tstation",
    title: "Tstation — AI 개발환경 통합 플랫폼",
    transition: "fly",
    art: "radial-gradient(circle at 55% 40%, rgba(0,180,255,0.42), transparent 60%), radial-gradient(circle at 20% 80%, rgba(0,229,180,0.25), transparent 55%)",
    notes: "챕터4 진입. AI 코딩 교육 배경 영상 위로 'Tstation' Kinetic Reveal. '복잡한 설정 없이 원클릭 실습' 인상 형성.",
  },
  {
    id: "instant-setup",
    section: "Tstation",
    title: "Instant Setup: 6시간 → 1초",
    transition: "fade",
    art: "linear-gradient(110deg, rgba(30,30,36,0.85) 0 45%, rgba(6,40,32,0.85) 45% 100%)",
    notes: "IaC 인포그래픽 장표. 스텝: ①구간A 전통 방식 4~6시간 5단계 → ②구간B 코드가 곧 인프라 → ③구간C 1초 접속. 각 스텝이 영상 구간(또는 HTML 폴백)을 재생하고 하단 자막 칩이 교체됨. 발표 템포를 스텝으로 제어.",
  },
  {
    id: "tstation-features",
    section: "Tstation",
    title: "Tstation 6대 특징",
    transition: "push",
    art: "linear-gradient(150deg, rgba(0,120,180,0.35), rgba(14,20,40,0.5))",
    notes: "벤토 그리드. 스텝: ①헤드라인·리드문 → ②상단 3카드 → ③하단 3카드(+좌상→우하 자동 데모 시연). 카드 hover 시 특징별 마이크로 데모 1회 재생.",
  },
  {
    id: "cas",
    section: "CAS",
    title: "CAS — All-in-One 교육 플랫폼",
    transition: "fly",
    art: "radial-gradient(circle at 50% 40%, rgba(79,124,255,0.4), transparent 60%), radial-gradient(circle at 80% 75%, rgba(124,92,255,0.28), transparent 55%)",
    notes: "챕터5 진입. 대학 강의실 배경 영상 위로 'CAS' Kinetic Reveal. 스텝②에서 강의·학습·과제·실습·평가 5개 키워드 칩이 라인으로 연결(All-in-One 시각화).",
  },
  {
    id: "cas-platform",
    section: "CAS",
    title: "CAS 통합 학습관리",
    transition: "fade",
    art: "linear-gradient(120deg, rgba(40,60,140,0.5), rgba(20,28,64,0.6))",
    notes: "허브+탭 목업. 스텝: ①헤드라인·리드문 → ②허브 프레임+탭 4종(첫 탭 활성) → ③탭 자동 순회 시연(1바퀴) → ④공통 기반 배지 3종+브릿지 라인. 탭 클릭/hover/↑↓로 전환. ※연출된 예시 화면.",
  },
];
