/* content.js — 슬라이드 메타데이터 (Content Driven 원칙)
 * 씬의 마크업은 index.html에, 목차·노트·전환 설정은 여기서 관리한다. */
window.CONTENT = [
  {
    id: "opening",
    section: "Opening",
    title: "AI Native Campus로의 전환",
    transition: "fade",
    art: "radial-gradient(circle at 30% 25%, rgba(79,124,255,0.5), transparent 60%), radial-gradient(circle at 80% 75%, rgba(0,229,255,0.3), transparent 55%)",
    notes: "발표 첫인상. 캠퍼스 영상 위 타이틀 리빌과 거버닝 카피가 자동으로 이어짐. 'AI를 도입하는 대학에서, AI로 태어나는 대학으로'를 힘 있게 낭독.",
  },
  {
    id: "context",
    section: "Background",
    title: "AI는 이미 학습과 행정의 기본 도구가 되었다",
    transition: "blur-fade",
    art: "linear-gradient(100deg, rgba(26,29,38,0.9) 0 50%, rgba(20,34,77,0.9) 50% 100%)",
    notes: "금지의 시대→권장의 시대 인식 전환. 마우스를 좌우로 움직이며 Before/After를 보여줄 것. 진행 입력 한 번이면 After 리빌과 학습·연구·행정·업무 칩이 자동으로 이어짐.",
  },
  {
    id: "voices",
    section: "Problem",
    title: "현장의 목소리",
    transition: "push",
    art: "radial-gradient(circle at 50% 40%, rgba(124,92,255,0.45), transparent 60%)",
    notes: "학생→교수→운영자 순서로 증언 카드 회전. 각 페르소나 대사를 1개씩만 읽고 템포 유지. 마지막 결론 카피: '뒷받침할 AI 통합 인프라가 없다'.",
  },
  {
    id: "painpoints",
    section: "Problem",
    title: "대학이 안고 있는 복합적인 Pain Point",
    transition: "fade",
    art: "radial-gradient(circle at 25% 30%, rgba(255,92,122,0.35), transparent 55%), radial-gradient(circle at 75% 70%, rgba(79,124,255,0.3), transparent 55%)",
    notes: "카드 4장이 자동으로 하나씩 등장하고 얽힘 라인이 이어서 그려짐. 각 문제를 짚은 뒤 '문제는 서로 얽혀 있다' 강조 — 개별 해결이 불가능함을 설득.",
  },
  {
    id: "solution",
    section: "Solution",
    title: "단 하나의 통합 인프라",
    transition: "morph",
    art: "radial-gradient(circle at 50% 50%, rgba(0,229,255,0.4), transparent 58%)",
    notes: "흩어진 전공·자원 노드를 보여준 뒤(호버로 툴팁 시연 가능), 스텝2에서 중앙으로 응집. 핵심 문장: '모든 전공의 기본 도구로 내재화한다'.",
  },
  {
    id: "architecture",
    section: "Architecture",
    title: "AI 인프라 표준 프레임워크",
    transition: "zoom",
    art: "linear-gradient(160deg, rgba(39,87,214,0.35), rgba(124,92,255,0.25) 55%, rgba(12,138,95,0.25))",
    notes: "스텝①: 이용자 트랙 3장 등장. 진행 입력 한 번(스텝②)이면 API/vGPU 커넥터+Slurm/K8s → 내부 모듈 4종 → VDI → 외부 LLM·전체 조망이 자동으로 이어짐(약 7초). 조망 상태에서 트랙에 호버하면 자원 경로가 하이라이트됨.",
  },
  /* ══════ 02 덱 · 기술 상세 ══════ */
  {
    id: "dstation",
    section: "Dstation",
    title: "Dstation — VDI",
    transition: "fly",
    art: "radial-gradient(circle at 65% 40%, rgba(79,124,255,0.5), transparent 60%)",
    notes: "챕터1 진입. VDI 배경 영상 위 타이틀 자동 리빌. '시공간 제약 없는 학습'을 강조하고 다음 장에서 개념을 설명.",
  },
  {
    id: "vdi-concept",
    section: "Dstation",
    title: "데스크톱 가상화 개념",
    transition: "fade",
    art: "linear-gradient(140deg, rgba(39,87,214,0.35), rgba(0,166,196,0.25))",
    notes: "스텝: ①좌측 메시지 → ②Cloud Center → ③Any Where/Device 칩 + 자동 시연 1회 → ④핵심 카피 강조. 단말 칩에 호버하면 가상PC로 파티클 왕복 + 미러링 시연 가능.",
  },
  {
    id: "estation",
    section: "Estation",
    title: "Estation — GPU Slicing",
    transition: "fly",
    art: "radial-gradient(circle at 60% 45%, rgba(25,201,141,0.45), transparent 60%)",
    notes: "챕터2 진입. 스텝②에서 '9배'가 카운트업되며 확대 강조 — '고가의 GPU 활용률이 9배 향상'을 힘 있게.",
  },
  {
    id: "gpu-slicing",
    section: "Estation",
    title: "유동적 vGPU 분할 비교",
    transition: "wipe",
    art: "linear-gradient(100deg, rgba(255,92,122,0.3) 0 48%, rgba(25,201,141,0.35) 52% 100%)",
    notes: "스텝: ①전통 방식(15%) → ②Tilon GPU 등장 → ③8장 레이어 슬라이싱 분해 + 워크로드 연결 → ④활용률 게이지 레이스(15% vs 90%). 우측 레이어에 호버하면 레이어:워크로드 매핑 시연.",
  },
  {
    id: "daas-value",
    section: "Estation",
    title: "DaaS + GPU Slicing 가치",
    transition: "push",
    art: "radial-gradient(circle at 40% 60%, rgba(25,201,141,0.4), transparent 58%)",
    notes: "스텝: 가치①(활용률 카운터)→②(고성능 워크로드)→③(64FPS/8K 프레임 비교)→④MIG 비교표→⑤활용 분야+결론. 5FPS vs 64FPS 시뮬레이션 박스로 체감 비교.",
  },
  {
    id: "istation",
    section: "iStation",
    title: "iStation — Sovereign AI",
    transition: "fly",
    art: "radial-gradient(circle at 60% 40%, rgba(180,79,255,0.45), transparent 60%)",
    notes: "챕터3 진입. Internal AI / AI Router / Tokenizer 3개 키워드 칩이 순차 리빌. '데이터 주권' 인상 형성.",
  },
  {
    id: "istation-features",
    section: "iStation",
    title: "iStation 3대 특징",
    transition: "fade",
    art: "linear-gradient(150deg, rgba(124,92,255,0.4), rgba(30,20,64,0.5))",
    notes: "스텝: ①카드 3장 등장 → ②일괄 플립 시연(뒷면 상세 노출) → ③핵심 문장 강조. 카드 호버=플립, 클릭=고정.",
  },
  /* ══════ 05 덱 · iStation 심화 (기능명세서 v2.0 · 4장) ══════ */
  {
    id: "econ-compare",
    section: "iStation",
    title: "멀티 LLM vs iStation 경제성 비교",
    transition: "morph",
    art: "radial-gradient(circle at 26% 40%, rgba(255,120,103,0.28), transparent 55%), radial-gradient(circle at 78% 60%, rgba(24,215,232,0.30), transparent 58%)",
    notes: "동일 질의가 두 시스템으로 분기하는 서사. 스텝: ①동일 질의 입력·분기 → ②멀티 LLM 외부 호출(비용 계기판 카운트업·토큰 유출 파티클) → ③iStation 내부 처리(External API Call 0) → ④경제성 결론. 표현 정책: '외부 API 토큰 비용 미발생'이며 인프라 비용은 별도(하단 주석). '전체 비용 0원' 오인 문구 금지. →키만으로 진행.",
  },
  {
    id: "ai-routing",
    section: "iStation",
    title: "iStation AI Routing",
    transition: "fade",
    art: "linear-gradient(120deg, rgba(24,215,232,0.14), rgba(57,120,255,0.12) 55%, rgba(140,108,255,0.14))",
    notes: "Internal First · Intelligent Routing. 스텝: ①입력 4종 → ②Internal VLM 우선 실행(외부 경로 비활성) → ③Quality Gate 92% 내부 답변 → ④예외 시 Routing(Web Search·승인된 Public LLM, 이때만 Token Meter·Governance 하이라이트) → ⑤Coordinator 통합. 핵심: '내부 AI를 먼저, 외부 AI는 필요한 순간에만'.",
  },
  {
    id: "open-weight-benchmark",
    section: "iStation",
    title: "Open-Weight AI, 경쟁력 있는 성능",
    transition: "fade",
    art: "radial-gradient(circle at 50% 30%, rgba(57,120,255,0.22), transparent 60%)",
    notes: "Artificial Analysis Intelligence Index(v4.1, 2026-07 스냅샷) 데이터를 사이트 형태 그대로 재현한 막대차트. 오픈 웨이트(파랑)와 상용(검정)이 상위권에서 경쟁 — 특히 GLM-5.2 등 오픈 모델이 일부 상용 모델을 앞서는 지점을 짚을 것. 용어는 sLLM이 아닌 Open-Weight. 출처 상시 표시·점수 무수정. 진행 입력 1회로 다음 장.",
  },
  {
    id: "hierarchical-ai",
    section: "iStation",
    title: "iStation 계층적 다중 AI 체계",
    transition: "zoom",
    art: "linear-gradient(160deg, rgba(57,120,255,0.22), rgba(140,108,255,0.16) 55%, rgba(35,215,160,0.16))",
    notes: "OIGP 4계층 구조도(자체 렌더). 좌측 상세 카드(Organization→Internal→Group→Personal)가 핵심 — 각 계층 역할을 짚고, 우측 흐름도로 정책이 위→아래로 상속됨을 설명. 하단 공통 기반(데이터 통합·보안 / 거버넌스 / 모니터링 / 상호 피드백) 언급. 정적 화면, 진행 입력 1회로 다음 장.",
  },
  {
    id: "scheduling",
    section: "iStation",
    title: "지능형 자원 스케줄링",
    transition: "blur-fade",
    art: "linear-gradient(100deg, rgba(18,50,90,0.6) 0 50%, rgba(5,7,15,0.8) 50% 100%)",
    notes: "시그니처 장표. 스텝: ①주간(수백 명 미세 분할) → ②야간 전환(대규모 집중 할당) → ③24시간 결론. GPU 코어·매트릭스·연구 블록에 호버 툴팁.",
  },
  {
    id: "jeju-case",
    section: "Case",
    title: "제주대학교 Sovereign AI 구축",
    transition: "push",
    art: "linear-gradient(120deg, rgba(60,33,120,0.55), rgba(28,20,64,0.6))",
    notes: "스텝: ①인사말 타이핑 → ②질문/답변 데모 재생(6초 이내) → ③특징 노드 4종 연결 → ④의의 강조. 노드 호버 시 채팅에서 해당 특징 위치가 하이라이트. ※연출된 예시임을 안내.",
  },
  {
    id: "closing",
    section: "Closing",
    title: "자체 AI 인프라 = 정부사업 가산점",
    transition: "particle",
    art: "radial-gradient(circle at 50% 45%, rgba(0,229,255,0.35), transparent 58%), radial-gradient(circle at 30% 70%, rgba(79,124,255,0.3), transparent 55%)",
    notes: "클로징. 스텝: ①헤드라인 → ②기존 방식(단순 소비) → ③자체 보유(가치 4종) → ④정부사업 무기 + 최종 메시지(파티클 응집). 마지막 입력 시 Overview가 열려 Q&A 대응.",
  },
  {
    id: "tstation",
    section: "Tstation",
    title: "Tstation — AI 개발환경 통합 플랫폼",
    transition: "fly",
    art: "radial-gradient(circle at 55% 40%, rgba(0,180,255,0.42), transparent 60%), radial-gradient(circle at 20% 80%, rgba(0,229,180,0.25), transparent 55%)",
    notes: "챕터4 진입. AI 코딩 교육 배경 영상 위로 'Tstation' Kinetic Reveal. '복잡한 설정 없이 원클릭 실습' 인상 형성.",
  },
  {
    id: "instant-setup",
    section: "Tstation",
    title: "Instant Setup — IaC 표준 개발환경",
    transition: "fade",
    art: "linear-gradient(110deg, rgba(30,30,36,0.85) 0 45%, rgba(6,40,32,0.85) 45% 100%)",
    notes: "IaC 변환 다이어그램(PPT_AID scene-14 컨셉). 진입 시 클릭 없이 자동 재생 — 좌측 혼돈(버전 충돌·CUDA 오류·패키지 지옥·환경 편차)이 흐릿하게 떠오르고 → 중앙 Tstation(INFRA AS CODE) 코어가 점등 → 우측 표준 스택(Jupyter·VSCode·GPU·Memory·Dataset·Source Code)이 정렬되어 등장. 핵심 메시지: '코드가 곧 인프라 — 접속 즉시 표준 개발환경'.",
  },
  {
    id: "tstation-features",
    section: "Tstation",
    title: "Tstation 6대 특징",
    transition: "push",
    art: "linear-gradient(150deg, rgba(0,120,180,0.35), rgba(14,20,40,0.5))",
    notes: "벤토 그리드. 스텝: ①헤드라인·리드문 → ②상단 3카드 → ③하단 3카드(+좌상→우하 자동 데모 시연). 카드 hover 시 특징별 마이크로 데모 1회 재생.",
  },
  {
    id: "ts001",
    section: "Tstation",
    title: "Tstation 시연 ①",
    transition: "fade",
    art: "radial-gradient(circle at 50% 50%, rgba(0,180,255,0.42), transparent 60%)",
    notes: "Tstation 시연 영상(TS001) 전체화면 자동재생. 진입 시 처음부터 자동 재생·루프. 필요 시 화면을 보며 구두 설명, 다음 입력으로 넘어감.",
  },
  {
    id: "ts002",
    section: "Tstation",
    title: "Tstation 시연 ②",
    transition: "fade",
    art: "radial-gradient(circle at 50% 50%, rgba(0,229,180,0.4), transparent 60%)",
    notes: "Tstation 시연 영상(TS002) 전체화면 자동재생. 진입 시 처음부터 자동 재생·루프.",
  },
  /* ══════ 06 덱 · Colab vs Tstation (Tstation UI설계 작업지시서 · 8장) ══════ */
  {
    id: "cl-intro",
    section: "Colab vs Tstation",
    title: "Google Colab, 대학 정규수업에도 충분할까요?",
    transition: "push",
    art: "linear-gradient(100deg, rgba(247,183,49,0.28) 0 45%, rgba(0,180,255,0.3) 55% 100%)",
    notes: "표현 원칙: Colab을 부정하지 않음 — '개인·단기 실습에는 편리하지만, 정규수업에는 운영체계가 필요하다'. 스텝: ①Colab 장점 → ②대학 수업 요구 조건 → ③핵심 문제 카드 5장. 카드 클릭=해당 상세 페이지 이동, hover=교육 현장 영향 한 줄.",
  },
  {
    id: "cl-runtime",
    section: "Colab vs Tstation",
    title: "런타임 종료와 비영속 환경",
    transition: "fade",
    art: "linear-gradient(120deg, rgba(255,92,122,0.25), rgba(255,159,67,0.22) 60%, rgba(20,26,48,0.6))",
    notes: "진입 시 수업 타임라인 8단계 자동 재생 — 모델 학습 78%에서 런타임 종료 → 루프백 화살표(처음부터 다시). '다시 재생' 버튼으로 반복 시연. 스텝: ②교육 현장 영향 → ③Tstation 연결 문장. 주의: '무조건 12시간마다 종료' 같은 단정 표현 금지(지양 표현 원칙).",
  },
  {
    id: "cl-data",
    section: "Colab vs Tstation",
    title: "데이터 접근 안정성",
    transition: "blur-fade",
    art: "radial-gradient(circle at 42% 45%, rgba(247,183,49,0.3), transparent 55%), radial-gradient(circle at 80% 70%, rgba(255,92,122,0.2), transparent 55%)",
    notes: "외부 저장소 1개에 학생 다수 동시 접속 구조. 스텝②에서 30→60→100명 자동 확대 — 부하 게이지 상승, 지연(주황)·실패(빨강) 증가. 버튼으로 수동 전환 가능. '장애'가 아니라 '교육 운영의 불확실성'으로 설명할 것(시각 구성 원칙).",
  },
  {
    id: "cl-collab",
    section: "Colab vs Tstation",
    title: "협업 및 장기 프로젝트 운영 한계",
    transition: "fade",
    art: "linear-gradient(140deg, rgba(0,180,255,0.2), rgba(124,92,255,0.22) 55%, rgba(255,92,122,0.18))",
    notes: "캡스톤 4인 팀(전처리·모델·UI·백엔드) 실행환경 비교. 스텝: ①학생 카드 4장 → ②버전·경로 차이 하이라이트 → ③통합 시도 충돌('내 PC에서는 실행됨') → ④Tstation 공동 개발공간 미리보기. 핵심: 'Notebook 공유 ≠ 공동 개발환경'.",
  },
  {
    id: "cl-gpu",
    section: "Colab vs Tstation",
    title: "대학 내부 GPU 활용 한계",
    transition: "wipe",
    art: "linear-gradient(100deg, rgba(255,159,67,0.25) 0 48%, rgba(0,229,180,0.28) 52% 100%)",
    notes: "좌: 학과·연구실에 흩어진 GPU(과부하 92% vs 유휴 8%) + 외부 Colab 미연결. 우: 중앙 GPU Pool + 수업 시간표 기반 배분. 스텝②에서 자원이 Pool로 이동(24 GPU 통합), 스텝③에서 수업·연구·캡스톤·야간·산학에 배분. 핵심 문구: '소유보다 배분'.",
  },
  {
    id: "cl-monitor",
    section: "Colab vs Tstation",
    title: "학생 진행 현황 관리 한계",
    transition: "fade",
    art: "radial-gradient(circle at 35% 45%, rgba(0,180,255,0.25), transparent 55%), radial-gradient(circle at 78% 55%, rgba(255,159,67,0.25), transparent 55%)",
    notes: "교수자가 확인할 질문 7개 vs 흩어진 시스템 7개(Colab·Drive·LMS·Classroom·이메일·메신저·과제 시스템)가 점선으로 얽힘. 스텝③에서 Tstation 교수자 대시보드 미리보기(오류 2명 즉시 식별). ※대시보드는 연출된 예시 화면.",
  },
  {
    id: "cl-solution",
    section: "Colab vs Tstation",
    title: "Tstation 해결 구조 및 비교",
    transition: "morph",
    art: "radial-gradient(circle at 30% 40%, rgba(0,180,255,0.35), transparent 58%), radial-gradient(circle at 75% 65%, rgba(0,229,180,0.28), transparent 55%)",
    notes: "앞 5개 문제 ↔ Tstation 5개 기능 직접 연결(상단 문제 칩 hover/클릭 시 해당 기능 강조). '수업 시작/종료' 버튼으로 GPU 자동 할당·회수 시연. 스텝: ①해결 구조 → ②Colab/Tstation 비교표 8항목 → ③핵심 카피 '편리함은 유지하고 운영·관리를 더한다'.",
  },
  {
    id: "cl-effect",
    section: "Colab vs Tstation",
    title: "도입 효과 및 제안 마무리",
    transition: "zoom",
    art: "radial-gradient(circle at 50% 40%, rgba(0,180,255,0.35), rgba(0,229,180,0.16) 45%, transparent 65%)",
    notes: "수혜 대상별 효과: 학생→교수자→전산조직→경영진 순차 등장. 스텝②에서 핵심 문구 3개(수업=동일 GPU 환경 / 연구=유휴 GPU / 대학=투자 효율), 스텝③ CTA — 데모 보기(ts001 이동)·구축 사례(제주대 이동)·도입 상담/제안서(메일).",
  },
  {
    id: "cas",
    section: "CAS",
    title: "CAS — All-in-One 교육 플랫폼",
    transition: "fly",
    art: "radial-gradient(circle at 50% 40%, rgba(79,124,255,0.4), transparent 60%), radial-gradient(circle at 80% 75%, rgba(124,92,255,0.28), transparent 55%)",
    notes: "챕터5 진입. 대학 강의실 배경 영상 위로 'CAS' Kinetic Reveal. 스텝②에서 강의·학습·과제·실습·평가 5개 키워드 칩이 라인으로 연결(All-in-One 시각화).",
  },
  {
    id: "cas-platform",
    section: "CAS",
    title: "CAS 통합 학습관리",
    transition: "fade",
    art: "linear-gradient(120deg, rgba(40,60,140,0.5), rgba(20,28,64,0.6))",
    notes: "허브+탭 목업. 스텝: ①헤드라인·리드문 → ②허브 프레임+탭 4종(첫 탭 활성) → ③탭 자동 순회 시연(1바퀴) → ④공통 기반 배지 3종+브릿지 라인. 탭 클릭/hover/↑↓로 전환. ※연출된 예시 화면.",
  },
  {
    id: "cbt001",
    section: "CAS",
    title: "CBT 시연 ①",
    transition: "fade",
    art: "radial-gradient(circle at 50% 50%, rgba(79,124,255,0.4), transparent 60%)",
    notes: "CBT 시연 영상(CBT001) 전체화면 자동재생. 진입 시 처음부터 자동 재생·루프.",
  },
  {
    id: "cbt002",
    section: "CAS",
    title: "CBT 시연 ②",
    transition: "fade",
    art: "radial-gradient(circle at 50% 50%, rgba(124,92,255,0.4), transparent 60%)",
    notes: "CBT 시연 영상(CBT002) 전체화면 자동재생. 진입 시 처음부터 자동 재생·루프.",
  },
  {
    id: "brand-film",
    section: "Brand",
    title: "TILON 브랜드 필름 — Connected by TILON",
    transition: "fade",
    art: "radial-gradient(circle at 50% 45%, rgba(79,124,255,0.42), rgba(0,229,255,0.18) 45%, transparent 65%)",
    notes: "TILON 브랜드 필름(AI 생성, 15초 루프) 전체화면 자동재생. FPV 드론이 미래 도시를 관통하며 Dstation~Vstation → TILON 타워 → Center 시리즈 순으로 BI 노출. 12초부터 엔딩 카피 'Beyond Workspace, Into AI-Native Infrastructure' 페이드인(루프 시 재동기화).",
  },
];
